# Generated by Django 4.2.5 on 2023-09-22 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iconImage', models.ImageField(upload_to='static/images')),
                ('serviceTitle', models.CharField(max_length=255)),
                ('serviceDesc', models.TextField()),
            ],
        ),
    ]
