# Generated by Django 4.2.5 on 2023-09-26 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_guard'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=255)),
                ('cemail', models.CharField(max_length=255)),
                ('cphone', models.CharField(max_length=10)),
                ('cmsg', models.TextField()),
            ],
        ),
    ]
