# Generated by Django 4.2.5 on 2023-09-27 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rname', models.CharField(max_length=255)),
                ('runame', models.CharField(max_length=255)),
                ('remail', models.CharField(max_length=255)),
                ('rpass', models.CharField(max_length=100)),
            ],
        ),
    ]
