# Generated by Django 4.2.5 on 2023-09-27 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_registration'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aImage', models.ImageField(upload_to='static/images')),
                ('aTitle', models.CharField(max_length=255)),
                ('aDesc', models.TextField()),
            ],
        ),
    ]
