# Generated by Django 4.2.5 on 2023-10-06 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0006_client'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eid', models.CharField(max_length=7)),
                ('ename', models.CharField(max_length=255)),
                ('eemail', models.EmailField(max_length=255)),
                ('econtact', models.CharField(max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='Client',
        ),
    ]
