# Generated by Django 4.2.5 on 2023-10-09 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0007_employee_delete_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='eid',
            field=models.IntegerField(max_length=7),
        ),
    ]
